# Generated by Django 5.2.17 on 2026-09-15 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('device_type', models.CharField(choices=[('cisco_ios', 'Cisco IOS'), ('cisco_nxos', 'Cisco NX-OS'), ('linux', 'Linux'), ('other', 'Other')], default='cisco_ios', max_length=50)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('enabled', models.BooleanField(default=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
