# Generated by Django 5.2.17 on 2026-09-16 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_interface'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='snmp_community',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='device',
            name='snmp_version',
            field=models.CharField(choices=[('2c', 'SNMP v2c'), ('3', 'SNMP v3')], default='2c', max_length=10),
        ),
    ]
