# Generated by Django 5.2.17 on 2026-09-16 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_device_snmp_community_device_snmp_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='system_description',
            field=models.TextField(blank=True),
        ),
    ]
