# Generated by Django 5.2.17 on 2026-09-16 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_device_system_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='last_checked',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('online', 'Online'), ('offline', 'Offline')], default='unknown', max_length=20),
        ),
    ]
